Slick_button_text:
  default: "Image Gallery"
  description:
    en: Enter the text for the title of the button in the composer.
Slick_add_images_prompt:
  default: "Add images"
  description:
    en: Enter the placeholder text that appears in the composer after the user clicks the button.
Slick_button_icon:
  default: "far-image"
  description:
    en: Choose an icon for the slick gallery button in the composer.
Slick_prev_icon:
  default: "chevron-left"
  description:
    en: Choose an icon for the slick previous button.
Slick_next_icon:
  default: "chevron-right"
  description:
    en: Choose an icon for the slick next button.
